name: check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Check type
        run: pnpm type

      - name: Check unit test
        run: pnpm test
