name: coverage

on:
  push:
    tags:
      - 'v*'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment.yml

      - name: Build coverage reports
        run: |
          pnpm --filter=@white-block/types test:coverage
          pnpm --filter=white-block test:coverage

      # Push packages reports
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: core
          files: ./packages/core/coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: types
          files: ./packages/types/coverage/coverage-final.json
