name: docs

on:
  push:
    tags:
      - 'v*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build packages
        run: |
          pnpm --filter=@white-block/types build
          pnpm --filter=white-block build

      - name: Build document
        env:
          PLATFORM: GitHub
        run: pnpm docs:build

      - name: Deploy document
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          branch: gh-pages
          folder: docs/.vitepress/dist
          single-commit: true
          clean: true
          clean-exclude: |
            v1/*
            v1/**/*
            playground/*
            playground/**/*
  playground:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build packages
        run: pnpm --filter=white-block build

      - name: Build playground
        env:
          PLATFORM: GitHub
        run: pnpm play:build

      - name: Deploy Playground
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          branch: gh-pages
          folder: docs/.vitepress/dist/playground
          single-commit: true
          clean: true
          target-folder: playground
