name: tag

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: pnpm change:version

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./packages/core/package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push and tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git config user.name "ephemeras"
          git config user.email "ephemeras@qq.com"
          git add .
          git commit -m "chore: bump version" -n --allow-empty
          git config pull.rebase true
          git pull
          git push
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
