name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build coverage reports
        run: |
          pnpm --filter=@white-block/types build
          pnpm --filter=white-block build
          pnpm --filter=@white-block/types test:coverage
          pnpm --filter=white-block test:coverage

      # Push packages reports
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: core
          files: ./packages/core/coverage/coverage-final.json

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: types
          files: ./packages/types/coverage/coverage-final.json
