name: version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get version
        id: get_version
        run: echo "VERSION=$(node -p \"require\('./packages/core/package.json'\).version\")" >> $GITHUB_ENV

      - name: Get repository info
        id: get_owner_info
        run: |
          OWNER_INFO=$(curl -H "Authorization: token ${{ secrets.ACTIONS_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/owner)
          OWNER_NAME=$(echo $OWNER_INFO | jq -r '.login')
          OWNER_EMAIL=$(echo $OWNER_INFO | jq -r '.email')
          echo "OWNER_NAME=$OWNER_NAME" >> $GITHUB_ENV
          echo "OWNER_EMAIL=$OWNER_EMAIL" >> $GITHUB_ENV

      - name: Set git info
        run: |
          git config user.name ${{ env.OWNER_NAME }}
          git config user.email ${{ env.OWNER_EMAIL }}

      - name: Changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: pnpm change:version

      - name: Push and tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git add .
          git commit -m 'chore: bump version' -n --allow-empty
          git config pull.rebase true
          git pull
          git push
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
